package kr.loner.service_locator

enum class KeyUseCase {
    CREATE_SCHEDULE_USE_CASE,
    DELETE_SCHEDULE_USE_CASE,
    GET_SCHEDULE_GROUP_USE_CASE,
    GET_SCHEDULE_USE_CASE,
    UP_DATE_SCHEDULE_USE_CASE,
}